# Copyright 2016-2018 Micael Oliveira
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


ABINIT_NATIVE_IXC = {'0': [{}],
                     '1': [{'xc_functional_name': 'LDA_XC_TETER93'}],
                     '2': [{'xc_functional_name': 'LDA_X'},
                           {'xc_functional_name': 'LDA_C_PZ'}],
                     # 3 - LDA, old Teter rational polynomial parametrization (4/91)
                     '4': [{'xc_functional_name': 'LDA_X'},
                           {'xc_functional_name': 'LDA_C_WIGNER'}],
                     '5': [{'xc_functional_name': 'LDA_X'},
                           {'xc_functional_name': 'LDA_C_HL'}],
                     '6': [{'xc_functional_name': 'LDA_X'},
                           {'xc_functional_name': 'LDA_C_XALPHA'}],
                     '7': [{'xc_functional_name': 'LDA_X'},
                           {'xc_functional_name': 'LDA_C_PW'}],
                     # 8 - x-only part of the Perdew-Wang 92 functional
                     # 9 - x- and RPA correlation part of the Perdew-Wang 92 functional
                     # 10 - non-existent
                     '11': [{'xc_functional_name': 'GGA_X_PBE'},
                            {'xc_functional_name': 'GGA_C_PBE'}],
                     '12': [{'xc_functional_name': 'GGA_X_PBE'}],
                     '13': [{'xc_functional_name': 'GGA_X_LB'},
                            {'xc_functional_name': 'LDA_C_PW'}],
                     '14': [{'xc_functional_name': 'GGA_X_PBE_R'},
                            {'xc_functional_name': '?'}],
                     '15': [{'xc_functional_name': 'GGA_X_RPBE'},
                            {'xc_functional_name': '?'}],
                     '16': [{'xc_functional_name': 'GGA_XC_HCTH_93'}],
                     '17': [{'xc_functional_name': 'GGA_XC_HCTH_120'}],
                     '18': [{'xc_functional_name': 'GGA_X_B88'},
                            {'xc_functional_name': 'GGA_C_LYP'}],
                     '19': [{'xc_functional_name': 'GGA_X_B88'},
                            {'xc_functional_name': 'GGA_C_P86'}],
                     # 20 - Fermi-Amaldi xc ( -1/N Hartree energy, where N is the number of electrons per cell;
                     #      G=0 is not taken into account however), for TDDFT tests.
                     # 21 - same as 20, except that the xc-kernel is the LDA (ixc=1) one, for TDDFT tests.
                     # 22 - same as 20, except that the xc-kernel is the Burke-Petersilka-Gross hybrid, for
                     #      TDDFT tests.
                     '23': [{'xc_functional_name': 'GGA_X_WC'},
                            {'xc_functional_name': '?'}],
                     '24': [{'xc_functional_name': 'GGA_X_C09X'},
                            {'xc_functional_name': '?'}],
                     # 25 - non-existent
                     '26': [{'xc_functional_name': 'GGA_XC_HCTH_147'}],
                     '27': [{'xc_functional_name': 'GGA_XC_HCTH_407'}],
                     '28': [{'xc_functional_name': 'GGA_X_OPTX'},
                            {'xc_functional_name': 'GGA_C_LYP'}],
                     '40': [{'xc_functional_name': 'HF_X'}],
                     '41': [{'xc_functional_name': 'HYB_GGA_XC_PBEH'}],
                     '42': [{'xc_functional_name': 'HYB_GGA_XC_PBE0_13'}]
                     }

ABINIT_LIBXC_IXC = {"1":   {"xc_functional_name": "LDA_X"},
                    "2":   {"xc_functional_name": "LDA_C_WIGNER"},
                    "3":   {"xc_functional_name": "LDA_C_RPA"},
                    "4":   {"xc_functional_name": "LDA_C_HL"},
                    "5":   {"xc_functional_name": "LDA_C_GL"},
                    "6":   {"xc_functional_name": "LDA_C_XALPHA"},
                    "7":   {"xc_functional_name": "LDA_C_VWN"},
                    "8":   {"xc_functional_name": "LDA_C_VWN_RPA"},
                    "9":   {"xc_functional_name": "LDA_C_PZ"},
                    "10":  {"xc_functional_name": "LDA_C_PZ_MOD"},
                    "11":  {"xc_functional_name": "LDA_C_OB_PZ"},
                    "12":  {"xc_functional_name": "LDA_C_PW"},
                    "13":  {"xc_functional_name": "LDA_C_PW_MOD"},
                    "14":  {"xc_functional_name": "LDA_C_OB_PW"},
                    "15":  {"xc_functional_name": "LDA_C_2D_AMGB"},
                    "16":  {"xc_functional_name": "LDA_C_2D_PRM"},
                    "17":  {"xc_functional_name": "LDA_C_vBH"},
                    "18":  {"xc_functional_name": "LDA_C_1D_CSC"},
                    "19":  {"xc_functional_name": "LDA_X_2D"},
                    "20":  {"xc_functional_name": "LDA_XC_TETER93"},
                    "21":  {"xc_functional_name": "LDA_X_1D"},
                    "22":  {"xc_functional_name": "LDA_C_ML1"},
                    "23":  {"xc_functional_name": "LDA_C_ML2"},
                    "24":  {"xc_functional_name": "LDA_C_GOMBAS"},
                    "25":  {"xc_functional_name": "LDA_C_PW_RPA"},
                    "26":  {"xc_functional_name": "LDA_C_1D_LOOS"},
                    "27":  {"xc_functional_name": "LDA_C_RC04"},
                    "28":  {"xc_functional_name": "LDA_C_VWN_1"},
                    "29":  {"xc_functional_name": "LDA_C_VWN_2"},
                    "30":  {"xc_functional_name": "LDA_C_VWN_3"},
                    "31":  {"xc_functional_name": "LDA_C_VWN_4"},
                    "32":  {"xc_functional_name": "GGA_X_GAM"},
                    "33":  {"xc_functional_name": "GGA_C_GAM"},
                    "34":  {"xc_functional_name": "GGA_X_HCTH_A"},
                    "35":  {"xc_functional_name": "GGA_X_EV93"},
                    "36":  {"xc_functional_name": "HYB_MGGA_X_DLDF"},
                    "37":  {"xc_functional_name": "MGGA_C_DLDF"},
                    "38":  {"xc_functional_name": "GGA_X_BCGP"},
                    "39":  {"xc_functional_name": "GGA_C_BCGP"},
                    "40":  {"xc_functional_name": "GGA_X_LAMBDA_OC2_N"},
                    "41":  {"xc_functional_name": "GGA_X_B86_R"},
                    "42":  {"xc_functional_name": "MGGA_XC_ZLP"},
                    "43":  {"xc_functional_name": "LDA_XC_ZLP"},
                    "44":  {"xc_functional_name": "GGA_X_LAMBDA_CH_N"},
                    "45":  {"xc_functional_name": "GGA_X_LAMBDA_LO_N"},
                    "46":  {"xc_functional_name": "GGA_X_HJS_B88_V2"},
                    "47":  {"xc_functional_name": "GGA_C_Q2D"},
                    "48":  {"xc_functional_name": "GGA_X_Q2D"},
                    "49":  {"xc_functional_name": "GGA_X_PBE_MOL"},
                    "50":  {"xc_functional_name": "LDA_K_TF"},
                    "51":  {"xc_functional_name": "LDA_K_LP"},
                    "52":  {"xc_functional_name": "GGA_K_TFVW"},
                    "53":  {"xc_functional_name": "GGA_K_REVAPBEINT"},
                    "54":  {"xc_functional_name": "GGA_K_APBEINT"},
                    "55":  {"xc_functional_name": "GGA_K_REVAPBE"},
                    "56":  {"xc_functional_name": "GGA_X_AK13"},
                    "57":  {"xc_functional_name": "GGA_K_MEYER"},
                    "58":  {"xc_functional_name": "GGA_X_LV_RPW86"},
                    "59":  {"xc_functional_name": "GGA_X_PBE_TCA"},
                    "60":  {"xc_functional_name": "GGA_X_PBEINT"},
                    "61":  {"xc_functional_name": "GGA_C_ZPBEINT"},
                    "62":  {"xc_functional_name": "GGA_C_PBEINT"},
                    "63":  {"xc_functional_name": "GGA_C_ZPBESOL"},
                    "64":  {"xc_functional_name": "MGGA_XC_OTPSS_D"},
                    "65":  {"xc_functional_name": "GGA_XC_OPBE_D"},
                    "66":  {"xc_functional_name": "GGA_XC_OPWLYP_D"},
                    "67":  {"xc_functional_name": "GGA_XC_OBLYP_D"},
                    "68":  {"xc_functional_name": "GGA_X_VMT84_GE"},
                    "69":  {"xc_functional_name": "GGA_X_VMT84_PBE"},
                    "70":  {"xc_functional_name": "GGA_X_VMT_GE"},
                    "71":  {"xc_functional_name": "GGA_X_VMT_PBE"},
                    "72":  {"xc_functional_name": "MGGA_C_CS"},
                    "73":  {"xc_functional_name": "MGGA_C_MN12_SX"},
                    "74":  {"xc_functional_name": "MGGA_C_MN12_L"},
                    "75":  {"xc_functional_name": "MGGA_C_M11_L"},
                    "76":  {"xc_functional_name": "MGGA_C_M11"},
                    "77":  {"xc_functional_name": "MGGA_C_M08_SO"},
                    "78":  {"xc_functional_name": "MGGA_C_M08_HX"},
                    "79":  {"xc_functional_name": "GGA_C_N12_SX"},
                    "80":  {"xc_functional_name": "GGA_C_N12"},
                    "81":  {"xc_functional_name": "HYB_GGA_X_N12_SX"},
                    "82":  {"xc_functional_name": "GGA_X_N12"},
                    "83":  {"xc_functional_name": "GGA_C_REGTPSS"},
                    "84":  {"xc_functional_name": "GGA_C_OP_XALPHA"},
                    "85":  {"xc_functional_name": "GGA_C_OP_G96"},
                    "86":  {"xc_functional_name": "GGA_C_OP_PBE"},
                    "87":  {"xc_functional_name": "GGA_C_OP_B88"},
                    "88":  {"xc_functional_name": "GGA_C_FT97"},
                    "89":  {"xc_functional_name": "GGA_C_SPBE"},
                    "90":  {"xc_functional_name": "GGA_X_SSB_SW"},
                    "91":  {"xc_functional_name": "GGA_X_SSB"},
                    "92":  {"xc_functional_name": "GGA_X_SSB_D"},
                    "93":  {"xc_functional_name": "GGA_XC_HCTH_407P"},
                    "94":  {"xc_functional_name": "GGA_XC_HCTH_P76"},
                    "95":  {"xc_functional_name": "GGA_XC_HCTH_P14"},
                    "96":  {"xc_functional_name": "GGA_XC_B97_GGA1"},
                    "97":  {"xc_functional_name": "GGA_C_HCTH_A"},
                    "98":  {"xc_functional_name": "GGA_X_BPCCAC"},
                    "99":  {"xc_functional_name": "GGA_C_REVTCA"},
                    "100": {"xc_functional_name": "GGA_C_TCA"},
                    "101": {"xc_functional_name": "GGA_X_PBE"},
                    "102": {"xc_functional_name": "GGA_X_PBE_R"},
                    "103": {"xc_functional_name": "GGA_X_B86"},
                    "104": {"xc_functional_name": "GGA_X_HERMAN"},
                    "105": {"xc_functional_name": "GGA_X_B86_MGC"},
                    "106": {"xc_functional_name": "GGA_X_B88"},
                    "107": {"xc_functional_name": "GGA_X_G96"},
                    "108": {"xc_functional_name": "GGA_X_PW86"},
                    "109": {"xc_functional_name": "GGA_X_PW91"},
                    "110": {"xc_functional_name": "GGA_X_OPTX"},
                    "111": {"xc_functional_name": "GGA_X_DK87_R1"},
                    "112": {"xc_functional_name": "GGA_X_DK87_R2"},
                    "113": {"xc_functional_name": "GGA_X_LG93"},
                    "114": {"xc_functional_name": "GGA_X_FT97_A"},
                    "115": {"xc_functional_name": "GGA_X_FT97_B"},
                    "116": {"xc_functional_name": "GGA_X_PBE_SOL"},
                    "117": {"xc_functional_name": "GGA_X_RPBE"},
                    "118": {"xc_functional_name": "GGA_X_WC"},
                    "119": {"xc_functional_name": "GGA_X_MPW91"},
                    "120": {"xc_functional_name": "GGA_X_AM05"},
                    "121": {"xc_functional_name": "GGA_X_PBEA"},
                    "122": {"xc_functional_name": "GGA_X_MPBE"},
                    "123": {"xc_functional_name": "GGA_X_XPBE"},
                    "124": {"xc_functional_name": "GGA_X_2D_B86_MGC"},
                    "125": {"xc_functional_name": "GGA_X_BAYESIAN"},
                    "126": {"xc_functional_name": "GGA_X_PBE_JSJR"},
                    "127": {"xc_functional_name": "GGA_X_2D_B88"},
                    "128": {"xc_functional_name": "GGA_X_2D_B86"},
                    "129": {"xc_functional_name": "GGA_X_2D_PBE"},
                    "130": {"xc_functional_name": "GGA_C_PBE"},
                    "131": {"xc_functional_name": "GGA_C_LYP"},
                    "132": {"xc_functional_name": "GGA_C_P86"},
                    "133": {"xc_functional_name": "GGA_C_PBE_SOL"},
                    "134": {"xc_functional_name": "GGA_C_PW91"},
                    "135": {"xc_functional_name": "GGA_C_AM05"},
                    "136": {"xc_functional_name": "GGA_C_XPBE"},
                    "137": {"xc_functional_name": "GGA_C_LM"},
                    "138": {"xc_functional_name": "GGA_C_PBE_JRGX"},
                    "139": {"xc_functional_name": "GGA_X_OPTB88_VDW"},
                    "140": {"xc_functional_name": "GGA_X_PBEK1_VDW"},
                    "141": {"xc_functional_name": "GGA_X_OPTPBE_VDW"},
                    "142": {"xc_functional_name": "GGA_X_RGE2"},
                    "143": {"xc_functional_name": "GGA_C_RGE2"},
                    "144": {"xc_functional_name": "GGA_X_RPW86"},
                    "145": {"xc_functional_name": "GGA_X_KT1"},
                    "146": {"xc_functional_name": "GGA_XC_KT2"},
                    "147": {"xc_functional_name": "GGA_C_WL"},
                    "148": {"xc_functional_name": "GGA_C_WI"},
                    "149": {"xc_functional_name": "GGA_X_MB88"},
                    "150": {"xc_functional_name": "GGA_X_SOGGA"},
                    "151": {"xc_functional_name": "GGA_X_SOGGA11"},
                    "152": {"xc_functional_name": "GGA_C_SOGGA11"},
                    "153": {"xc_functional_name": "GGA_C_WI0"},
                    "154": {"xc_functional_name": "GGA_XC_TH1"},
                    "155": {"xc_functional_name": "GGA_XC_TH2"},
                    "156": {"xc_functional_name": "GGA_XC_TH3"},
                    "157": {"xc_functional_name": "GGA_XC_TH4"},
                    "158": {"xc_functional_name": "GGA_X_C09X"},
                    "159": {"xc_functional_name": "GGA_C_SOGGA11_X"},
                    "160": {"xc_functional_name": "GGA_X_LB"},
                    "161": {"xc_functional_name": "GGA_XC_HCTH_93"},
                    "162": {"xc_functional_name": "GGA_XC_HCTH_120"},
                    "163": {"xc_functional_name": "GGA_XC_HCTH_147"},
                    "164": {"xc_functional_name": "GGA_XC_HCTH_407"},
                    "165": {"xc_functional_name": "GGA_XC_EDF1"},
                    "166": {"xc_functional_name": "GGA_XC_XLYP"},
                    "167": {"xc_functional_name": "GGA_X_EB88"},
                    "168": {"xc_functional_name": "GGA_C_PBE_MOL"},
                    "169": {"xc_functional_name": "HYB_GGA_XC_PBE_MOL0"},
                    "170": {"xc_functional_name": "GGA_XC_B97_D"},
                    "171": {"xc_functional_name": "HYB_GGA_XC_PBE_SOL0"},
                    "172": {"xc_functional_name": "HYB_GGA_XC_PBEB0"},
                    "173": {"xc_functional_name": "GGA_XC_PBE1W"},
                    "174": {"xc_functional_name": "GGA_XC_MPWLYP1W"},
                    "175": {"xc_functional_name": "GGA_XC_PBELYP1W"},
                    "176": {"xc_functional_name": "HYB_GGA_XC_PBE_MOLB0"},
                    "177": {"xc_functional_name": "GGA_K_ABSP3"},
                    "178": {"xc_functional_name": "GGA_K_ABSP4"},
                    "182": {"xc_functional_name": "GGA_X_LBM"},
                    "183": {"xc_functional_name": "GGA_X_OL2"},
                    "184": {"xc_functional_name": "GGA_X_APBE"},
                    "185": {"xc_functional_name": "GGA_K_APBE"},
                    "186": {"xc_functional_name": "GGA_C_APBE"},
                    "187": {"xc_functional_name": "GGA_K_TW1"},
                    "188": {"xc_functional_name": "GGA_K_TW2"},
                    "189": {"xc_functional_name": "GGA_K_TW3"},
                    "190": {"xc_functional_name": "GGA_K_TW4"},
                    "191": {"xc_functional_name": "GGA_X_HTBS"},
                    "192": {"xc_functional_name": "GGA_X_AIRY"},
                    "193": {"xc_functional_name": "GGA_X_LAG"},
                    "194": {"xc_functional_name": "GGA_XC_MOHLYP"},
                    "195": {"xc_functional_name": "GGA_XC_MOHLYP2"},
                    "196": {"xc_functional_name": "GGA_XC_TH_FL"},
                    "197": {"xc_functional_name": "GGA_XC_TH_FC"},
                    "198": {"xc_functional_name": "GGA_XC_TH_FCFO"},
                    "199": {"xc_functional_name": "GGA_XC_TH_FCO"},
                    "200": {"xc_functional_name": "GGA_C_OPTC"},
                    "201": {"xc_functional_name": "MGGA_X_LTA"},
                    "202": {"xc_functional_name": "MGGA_X_TPSS"},
                    "203": {"xc_functional_name": "MGGA_X_M06_L"},
                    "204": {"xc_functional_name": "MGGA_X_GVT4"},
                    "205": {"xc_functional_name": "MGGA_X_TAU_HCTH"},
                    "206": {"xc_functional_name": "MGGA_X_BR89"},
                    "207": {"xc_functional_name": "MGGA_X_BJ06"},
                    "208": {"xc_functional_name": "MGGA_X_TB09"},
                    "209": {"xc_functional_name": "MGGA_X_RPP09"},
                    "210": {"xc_functional_name": "MGGA_X_2D_PRHG07"},
                    "211": {"xc_functional_name": "MGGA_X_2D_PRHG07_PRP10"},
                    "212": {"xc_functional_name": "MGGA_X_REVTPSS"},
                    "213": {"xc_functional_name": "MGGA_X_PKZB"},
                    "214": {"xc_functional_name": "MGGA_X_M05"},
                    "215": {"xc_functional_name": "MGGA_X_M05_2X"},
                    "216": {"xc_functional_name": "MGGA_X_M06_HF"},
                    "217": {"xc_functional_name": "MGGA_X_M06"},
                    "218": {"xc_functional_name": "MGGA_X_M06_2X"},
                    "219": {"xc_functional_name": "MGGA_X_M08_HX"},
                    "220": {"xc_functional_name": "MGGA_X_M08_SO"},
                    "221": {"xc_functional_name": "MGGA_X_MS0"},
                    "222": {"xc_functional_name": "MGGA_X_MS1"},
                    "223": {"xc_functional_name": "MGGA_X_MS2"},
                    "224": {"xc_functional_name": "HYB_MGGA_X_MS2H"},
                    "225": {"xc_functional_name": "MGGA_X_M11"},
                    "226": {"xc_functional_name": "MGGA_X_M11_L"},
                    "227": {"xc_functional_name": "MGGA_X_MN12_L"},
                    "229": {"xc_functional_name": "MGGA_C_CC06"},
                    "230": {"xc_functional_name": "MGGA_X_MK00"},
                    "231": {"xc_functional_name": "MGGA_C_TPSS"},
                    "232": {"xc_functional_name": "MGGA_C_VSXC"},
                    "233": {"xc_functional_name": "MGGA_C_M06_L"},
                    "234": {"xc_functional_name": "MGGA_C_M06_HF"},
                    "235": {"xc_functional_name": "MGGA_C_M06"},
                    "236": {"xc_functional_name": "MGGA_C_M06_2X"},
                    "237": {"xc_functional_name": "MGGA_C_M05"},
                    "238": {"xc_functional_name": "MGGA_C_M05_2X"},
                    "239": {"xc_functional_name": "MGGA_C_PKZB"},
                    "240": {"xc_functional_name": "MGGA_C_BC95"},
                    "241": {"xc_functional_name": "MGGA_C_REVTPSS"},
                    "242": {"xc_functional_name": "MGGA_XC_TPSSLYP1W"},
                    "243": {"xc_functional_name": "MGGA_X_MK00B"},
                    "244": {"xc_functional_name": "MGGA_X_BLOC"},
                    "245": {"xc_functional_name": "MGGA_X_MODTPSS"},
                    "246": {"xc_functional_name": "GGA_C_PBELOC"},
                    "247": {"xc_functional_name": "MGGA_C_TPSSLOC"},
                    "248": {"xc_functional_name": "HYB_MGGA_X_MN12_SX"},
                    "249": {"xc_functional_name": "MGGA_X_MBEEF"},
                    "250": {"xc_functional_name": "MGGA_X_MBEEFVDW"},
                    "254": {"xc_functional_name": "MGGA_XC_B97M_V"},
                    "255": {"xc_functional_name": "GGA_XC_VV10"},
                    "257": {"xc_functional_name": "MGGA_X_MVS"},
                    "258": {"xc_functional_name": "GGA_C_PBEFE"},
                    "259": {"xc_functional_name": "LDA_XC_KSDT"},
                    "260": {"xc_functional_name": "MGGA_X_MN15_L"},
                    "261": {"xc_functional_name": "MGGA_C_MN15_L"},
                    "262": {"xc_functional_name": "GGA_C_OP_PW91"},
                    "263": {"xc_functional_name": "MGGA_X_SCAN"},
                    "264": {"xc_functional_name": "HYB_MGGA_X_SCAN0"},
                    "265": {"xc_functional_name": "GGA_X_PBEFE"},
                    "266": {"xc_functional_name": "HYB_GGA_XC_B97_1p"},
                    "267": {"xc_functional_name": "MGGA_C_SCAN"},
                    "268": {"xc_functional_name": "HYB_MGGA_X_MN15"},
                    "269": {"xc_functional_name": "MGGA_C_MN15"},
                    "270": {"xc_functional_name": "GGA_X_CAP"},
                    "401": {"xc_functional_name": "HYB_GGA_XC_B3PW91"},
                    "402": {"xc_functional_name": "HYB_GGA_XC_B3LYP"},
                    "403": {"xc_functional_name": "HYB_GGA_XC_B3P86"},
                    "404": {"xc_functional_name": "HYB_GGA_XC_O3LYP"},
                    "405": {"xc_functional_name": "HYB_GGA_XC_mPW1K"},
                    "406": {"xc_functional_name": "HYB_GGA_XC_PBEH"},
                    "407": {"xc_functional_name": "HYB_GGA_XC_B97"},
                    "408": {"xc_functional_name": "HYB_GGA_XC_B97_1"},
                    "410": {"xc_functional_name": "HYB_GGA_XC_B97_2"},
                    "411": {"xc_functional_name": "HYB_GGA_XC_X3LYP"},
                    "412": {"xc_functional_name": "HYB_GGA_XC_B1WC"},
                    "413": {"xc_functional_name": "HYB_GGA_XC_B97_K"},
                    "414": {"xc_functional_name": "HYB_GGA_XC_B97_3"},
                    "415": {"xc_functional_name": "HYB_GGA_XC_MPW3PW"},
                    "416": {"xc_functional_name": "HYB_GGA_XC_B1LYP"},
                    "417": {"xc_functional_name": "HYB_GGA_XC_B1PW91"},
                    "418": {"xc_functional_name": "HYB_GGA_XC_mPW1PW"},
                    "419": {"xc_functional_name": "HYB_GGA_XC_MPW3LYP"},
                    "420": {"xc_functional_name": "HYB_GGA_XC_SB98_1a"},
                    "421": {"xc_functional_name": "HYB_GGA_XC_SB98_1b"},
                    "422": {"xc_functional_name": "HYB_GGA_XC_SB98_1c"},
                    "423": {"xc_functional_name": "HYB_GGA_XC_SB98_2a"},
                    "424": {"xc_functional_name": "HYB_GGA_XC_SB98_2b"},
                    "425": {"xc_functional_name": "HYB_GGA_XC_SB98_2c"},
                    "426": {"xc_functional_name": "HYB_GGA_X_SOGGA11_X"},
                    "427": {"xc_functional_name": "HYB_GGA_XC_HSE03"},
                    "428": {"xc_functional_name": "HYB_GGA_XC_HSE06"},
                    "429": {"xc_functional_name": "HYB_GGA_XC_HJS_PBE"},
                    "430": {"xc_functional_name": "HYB_GGA_XC_HJS_PBE_SOL"},
                    "431": {"xc_functional_name": "HYB_GGA_XC_HJS_B88"},
                    "432": {"xc_functional_name": "HYB_GGA_XC_HJS_B97X"},
                    "433": {"xc_functional_name": "HYB_GGA_XC_CAM_B3LYP"},
                    "434": {"xc_functional_name": "HYB_GGA_XC_TUNED_CAM_B3LYP"},
                    "435": {"xc_functional_name": "HYB_GGA_XC_BHANDH"},
                    "436": {"xc_functional_name": "HYB_GGA_XC_BHANDHLYP"},
                    "437": {"xc_functional_name": "HYB_GGA_XC_MB3LYP_RC04"},
                    "438": {"xc_functional_name": "HYB_MGGA_XC_M05"},
                    "439": {"xc_functional_name": "HYB_MGGA_XC_M05_2X"},
                    "440": {"xc_functional_name": "HYB_MGGA_XC_B88B95"},
                    "441": {"xc_functional_name": "HYB_MGGA_XC_B86B95"},
                    "442": {"xc_functional_name": "HYB_MGGA_XC_PW86B95"},
                    "443": {"xc_functional_name": "HYB_MGGA_XC_BB1K"},
                    "444": {"xc_functional_name": "HYB_MGGA_XC_M06_HF"},
                    "445": {"xc_functional_name": "HYB_MGGA_XC_MPW1B95"},
                    "446": {"xc_functional_name": "HYB_MGGA_XC_MPWB1K"},
                    "447": {"xc_functional_name": "HYB_MGGA_XC_X1B95"},
                    "448": {"xc_functional_name": "HYB_MGGA_XC_XB1K"},
                    "449": {"xc_functional_name": "HYB_MGGA_XC_M06"},
                    "450": {"xc_functional_name": "HYB_MGGA_XC_M06_2X"},
                    "451": {"xc_functional_name": "HYB_MGGA_XC_PW6B95"},
                    "452": {"xc_functional_name": "HYB_MGGA_XC_PWB6K"},
                    "453": {"xc_functional_name": "HYB_GGA_XC_MPWLYP1M"},
                    "454": {"xc_functional_name": "HYB_GGA_XC_REVB3LYP"},
                    "455": {"xc_functional_name": "HYB_GGA_XC_CAMY_BLYP"},
                    "456": {"xc_functional_name": "HYB_GGA_XC_PBE0_13"},
                    "457": {"xc_functional_name": "HYB_MGGA_XC_TPSSH"},
                    "458": {"xc_functional_name": "HYB_MGGA_XC_REVTPSSH"},
                    "459": {"xc_functional_name": "HYB_GGA_XC_B3LYPs"},
                    "460": {"xc_functional_name": "HYB_MGGA_XC_M08_HX"},
                    "461": {"xc_functional_name": "HYB_MGGA_XC_M08_SO"},
                    "462": {"xc_functional_name": "HYB_MGGA_XC_M11"},
                    "463": {"xc_functional_name": "HYB_GGA_XC_WB97"},
                    "464": {"xc_functional_name": "HYB_GGA_XC_WB97X"},
                    "465": {"xc_functional_name": "HYB_GGA_XC_LRC_WPBEH"},
                    "466": {"xc_functional_name": "HYB_GGA_XC_WB97X_V"},
                    "467": {"xc_functional_name": "HYB_GGA_XC_LCY_PBE"},
                    "468": {"xc_functional_name": "HYB_GGA_XC_LCY_BLYP"},
                    "469": {"xc_functional_name": "HYB_GGA_XC_LC_VV10"},
                    "470": {"xc_functional_name": "HYB_GGA_XC_CAMY_B3LYP"},
                    "471": {"xc_functional_name": "HYB_GGA_XC_WB97X_D"},
                    "472": {"xc_functional_name": "HYB_GGA_XC_HPBEINT"},
                    "473": {"xc_functional_name": "HYB_GGA_XC_LRC_WPBE"},
                    "474": {"xc_functional_name": "HYB_MGGA_X_MVSH"},
                    "475": {"xc_functional_name": "HYB_GGA_XC_B3LYP5"},
                    "476": {"xc_functional_name": "HYB_GGA_XC_EDF2"},
                    "477": {"xc_functional_name": "HYB_GGA_XC_CAP0"},
                    "478": {"xc_functional_name": "HYB_GGA_XC_LC_WPBE"},
                    "500": {"xc_functional_name": "GGA_K_VW"},
                    "501": {"xc_functional_name": "GGA_K_GE2"},
                    "502": {"xc_functional_name": "GGA_K_GOLDEN"},
                    "503": {"xc_functional_name": "GGA_K_YT65"},
                    "504": {"xc_functional_name": "GGA_K_BALTIN"},
                    "505": {"xc_functional_name": "GGA_K_LIEB"},
                    "506": {"xc_functional_name": "GGA_K_ABSP1"},
                    "507": {"xc_functional_name": "GGA_K_ABSP2"},
                    "508": {"xc_functional_name": "GGA_K_GR"},
                    "509": {"xc_functional_name": "GGA_K_LUDENA"},
                    "510": {"xc_functional_name": "GGA_K_GP85"},
                    "511": {"xc_functional_name": "GGA_K_PEARSON"},
                    "512": {"xc_functional_name": "GGA_K_OL1"},
                    "513": {"xc_functional_name": "GGA_K_OL2"},
                    "514": {"xc_functional_name": "GGA_K_FR_B88"},
                    "515": {"xc_functional_name": "GGA_K_FR_PW86"},
                    "516": {"xc_functional_name": "GGA_K_DK"},
                    "517": {"xc_functional_name": "GGA_K_PERDEW"},
                    "518": {"xc_functional_name": "GGA_K_VSK"},
                    "519": {"xc_functional_name": "GGA_K_VJKS"},
                    "520": {"xc_functional_name": "GGA_K_ERNZERHOF"},
                    "521": {"xc_functional_name": "GGA_K_LC94"},
                    "522": {"xc_functional_name": "GGA_K_LLP"},
                    "523": {"xc_functional_name": "GGA_K_THAKKAR"},
                    "524": {"xc_functional_name": "GGA_X_WPBEH"},
                    "525": {"xc_functional_name": "GGA_X_HJS_PBE"},
                    "526": {"xc_functional_name": "GGA_X_HJS_PBE_SOL"},
                    "527": {"xc_functional_name": "GGA_X_HJS_B88"},
                    "528": {"xc_functional_name": "GGA_X_HJS_B97X"},
                    "529": {"xc_functional_name": "GGA_X_ITYH"},
                    "530": {"xc_functional_name": "GGA_X_SFAT"},
                    "531": {"xc_functional_name": "HYB_MGGA_XC_WB97M_V"}
                    }